database:

  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: 1234

  # the JDBC URL
  url: jdbc:mysql://localhost:3306/trackify

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect